name: Audit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  bun:
    name: Bun Build and Test
    runs-on: ubuntu-latest
    container: oven/bun:slim
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Bun Install
        working-directory: bun
        run: bun install
      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: bun/node_modules
          key: ${{ runner.os }}-bun-modules-${{ hashFiles('bun/bun.lockb') }}
      - name: Bun Test
        working-directory: bun
        run: bun test --timeout 60000

  go:
    name: Go Test
    runs-on: ubuntu-latest
    container: golang:1.23.3
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.3'
      - name: Cache Go Modules
        uses: actions/cache@v3
        with:
          path: /go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go/go.sum') }}
      - name: Go Test
        working-directory: go
        run: go test ./...