name: Audit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  bun:
    name: Bun Test
    runs-on: ubuntu-latest
    container: oven/bun:slim
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Bun Install
        working-directory: bun
        run: bun install
      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: bun/node_modules
          key: ${{ runner.os }}-bun-modules-${{ hashFiles('bun/bun.lockb') }}
      - name: Bun Test
        working-directory: bun
        run: bun test --timeout 60000

  go:
    name: Go Test
    runs-on: ubuntu-latest
    container: golang:1.23.3
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.3"
      - name: Cache Go Modules
        uses: actions/cache@v3
        with:
          path: /go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go/go.sum') }}
      - name: Go Test
        working-directory: go
        run: go test ./...
  rust:
    runs-on: ubuntu-latest
    name: Rust Test
    steps:
      - uses: actions/checkout@v4
      - name: Set up cargo cache
        uses: actions/cache@v4
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('rust/**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - name: cargo test
        working-directory: rust
        run: cd rust && cargo test
      - name: cargo clippy
        working-directory: rust
        run: cargo clippy -- -D warnings
      - name: cargo fmt
        working-directory: rust
        run: cargo fmt --check
